#!/bin/zsh

KODIAQ="XW8JC6NS9MH402460"
CEED="XWEHN812AF0005914"
ACCENT="X7MCF41GP5M040859"

FGetVIN(){
	echo $1 | pbcopy
        echo VIN: $1 скопирован в буфер обмена
}

case $1 in
	kodiaq|KODIAQ|Kodiaq)
		FGetVIN $KODIAQ
		;;
	ceed|CEED|Ceed)
		FGetVIN $CEED
		;;
	accent|ACCENT|Accent)
		FGetVIN $ACCENT
		;;
	*)
		echo "Тут нет такой машины"
		;;
esac
